trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AzureStaticWebAppToken

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(deployment_token)
      app_location: '/'
      output_location: 'build'
    displayName: 'Deploy to Azure Static Web App'
