trigger:
  branches:
    include:
      - master   # or main, depending on your GitHub repo

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: StaticWebAppSecrets  # Make sure this variable group contains the secret token

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React app'

- script: |
    npm install -g @azure/static-web-apps-cli
    swa deploy build --app-name Frontend --env production --deployment-token $DEPLOY_TOKEN
  displayName: 'Deploy to Azure Static Web Apps'
  env:
    DEPLOY_TOKEN: $(StaticWebAppDeploymentToken)  # Pass secret token securely
