trigger:
  branches:
    include:
      - main   # or your deployment branch

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: StaticWebAppSecrets  # Your variable group name with deployment token

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # Node version to build React app
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React app'

- script: |
    npm install -g @azure/static-web-apps-cli
    swa deploy build --app-name Frontend --env production --deployment-token $StaticWebAppDeploymentToken
  displayName: 'Deploy to Azure Static Web Apps'
